version: "3.9"
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: urlshortener
      MYSQL_USER: urlshortener
      MYSQL_PASSWORD: urlshortener

#  url_shortener:
#    build: .
#    container_name: urlshortener
#    ports:
#      - "5000:5000"
#    depends_on:
#      - db
#    volumes:
#      - .:/app
#    environment:
#      - SECRET_KEY=83lk25j23l45j23oi45u235
#      - ENDPOINT_URL=http://dynamodb-local:8000
#      - AWS_DEFAULT_REGION=localhost
#      - AWS_ACCESS_KEY_ID=ekwt6j
#      - AWS_SECRET_ACCESS_KEY=hdzk5g
#      - FLASK_ENV=development

volumes:
  mysql_data: {}

